# Generated by Django 2.0.13 on 2019-05-02 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='text_type',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
